<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simple_podcast"
 *
 * Auto generated by Extension Builder 2018-02-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple Podcast',
    'description' => 'Simple Podcast Extension providing a RSS feed for iTunes, Soundcloud, Spotify and others. Also having a simple output of podcast channels using HTML5 media player. Based on Extbase and Fluid.',
    'category' => 'plugin',
    'author' => 'Paul Beck',
    'author_email' => 'hi@toll-paul.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
